version: '3.4'

services:

  blogocomv2:
    image: blogocomapiv2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080:80"
      - "4000:4000"
    depends_on:
            - postgresql_database
    networks:
     - uhpcompany

  postgresql_database:
    image: postgres:latest
    environment:
       POSTGRES_USER: root
       POSTGRES_PASSWORD: root
       POSTGRES_DB: BlogocomV2
    ports:
      - "5555:5432"
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
     - uhpcompany

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
     - uhpcompany

volumes:
  database-data:
  pgadmin:


networks:
  uhpcompany:
    driver: bridge
