// <auto-generated />
using System;
using BlogocomApiV2.Settings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BlogocomApiV2.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20211021122151_AddUser")]
    partial class AddUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("BlogocomApiV2.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsAccess")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<byte[]>("StoredSalt")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 10, 21, 15, 21, 50, 827, DateTimeKind.Unspecified).AddTicks(754), new TimeSpan(0, 3, 0, 0, 0)),
                            Email = "Madge54@yahoo.com",
                            FirstName = "Preston",
                            IsAccess = true,
                            Password = "AcvlO60SntLTg24Kfon2Dypz0Req/tWyHST8hZ0Yljk=",
                            Phone = "+380994444333",
                            StoredSalt = new byte[] { 80, 19, 190, 77, 38, 18, 236, 73, 57, 222, 141, 155, 65, 197, 29, 43 }
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 10, 21, 15, 21, 50, 837, DateTimeKind.Unspecified).AddTicks(3884), new TimeSpan(0, 3, 0, 0, 0)),
                            Email = "Alysson_Bayer29@yahoo.com",
                            FirstName = "Antonetta",
                            IsAccess = true,
                            Password = "AcvlO60SntLTg24Kfon2Dypz0Req/tWyHST8hZ0Yljk=",
                            Phone = "+380994444222",
                            StoredSalt = new byte[] { 80, 19, 190, 77, 38, 18, 236, 73, 57, 222, 141, 155, 65, 197, 29, 43 }
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 10, 21, 15, 21, 50, 845, DateTimeKind.Unspecified).AddTicks(5301), new TimeSpan(0, 3, 0, 0, 0)),
                            Email = "Carlee_Kemmer@hotmail.com",
                            FirstName = "Lia",
                            IsAccess = true,
                            Password = "AcvlO60SntLTg24Kfon2Dypz0Req/tWyHST8hZ0Yljk=",
                            Phone = "+380994444111",
                            StoredSalt = new byte[] { 80, 19, 190, 77, 38, 18, 236, 73, 57, 222, 141, 155, 65, 197, 29, 43 }
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
